### ISSUE TITLE
False positives in check for applying events for the wrong aggregate in CommittedEvents

### ISSUE THREAD

**Issue by smithmx** [dolittle-runtime/Runtime#147]
When trying to replay the state, CommittedEvents is throwing the EventBelongsToOtherEventSource exception because the check for the EventSourceId on the metadata is different from the EventSourceId on the aggregate (even though the string representations are the same).

This is using the mongo event store so I suspect the Guids are not the same even though the string versions are the same.

**Comment by smithmx** [comment]
This is actually to do with EventSourceId, ConceptAs<Guid>, equality and inheriting from EventSourceId.  We should have a chat about it. :-)

**Comment by einari** [comment]
Test comment from Trello
